import cookieParser from "cookie-parser";
import cors from "cors";
import "dotenv/config";
import express from "express";
import logger from "morgan";
import swaggerUi from "swagger-ui-express";
import connect from "./database/db";
import userRoutes from "./routes/user.routes";

// Import swagger output file (will be generated by swagger-autogen)
let swaggerFile: any;
try {
    swaggerFile = require('./swagger-output.json');
} catch (error) {
    console.log('Swagger file not found. Using fallback...');
    // Fallback basic swagger definition
    swaggerFile = {
        openapi: '3.0.0',
        info: {
            title: 'EV Maintenance API',
            version: '1.0.0',
            description: 'API for EV Maintenance Backend'
        },
        paths: {}
    };
}

// DB initialize
connect();

const app = express();

app.use(cors());
app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());

// Swagger documentation
if (swaggerFile) {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerFile, {
        customCss: '.swagger-ui .topbar { display: true }',
        customSiteTitle: 'EV Maintenance API Documentation',
        swaggerOptions: {
            persistAuthorization: true,
            displayRequestDuration: true,
            docExpansion: 'list',
            filter: true,
            showExtensions: true,
            tryItOutEnabled: true,
            url: undefined // This forces it to use the embedded spec
        },
        // Use CDN for assets in production
        customCssUrl: process.env.NODE_ENV === 'production' ? 'https://unpkg.com/swagger-ui-dist@latest/swagger-ui.css' : undefined,
        customJs: process.env.NODE_ENV === 'production' ? ['https://unpkg.com/swagger-ui-dist@latest/swagger-ui-bundle.js'] : undefined
    }));
}

// API Routes
app.use('/api', userRoutes);

// Root route redirect to API docs
app.get('/', (req, res) => {
    res.redirect('/api-docs');
});

// 404 handler
app.use((req, res) => {
    res.status(404).json({
        success: false,
        message: 'Route not found'
    });
});

// Only listen in development or when not running as serverless
if (process.env.NODE_ENV !== 'production') {
    app.listen(process.env.PORT ?? 3000, () => {
        console.log(`App listening on port ${process.env.PORT || 3000}`);
    });
}

export default app;
